### PR TITLE
OpenRefine 2.7 compatibility

### PR DESCRIPTION
**Pull request by stkenny**
Updated the Jena libraries for #119 . Jena 3 requires Java 8.

### CODE REVIEW

**Comment by tfmorris** [comment]
Can you expand on the compatibility implications of this? Does it pin the RDF extension to a specific version of OpenRefine, or is it backward compatible?

**Comment by stkenny** [comment]
It introduces a dependency on Java 8. To use with version 2.6 you would need to recompile OpenRefine with Java 8, so the distributed versions will not work.

**Comment by marco-brandizi** [comment]
I would coordinate this with OpenRefine developers. We are in 2017, Java 8 has been around for a couple of years already, it's reasonable to migrate to it and leave older versions behind.

**Comment by stkenny** [comment]
Yes, but I am having some dependency problems now though which are potentially the cause of #114. It might be easier if I moved it to Maven.

**Comment by stkenny** [comment]
Because of problems with Xerces I could only get the vocabulary importing to work if I updated OpenRefine to use a more recent version of Jetty (9.4). The fork for that is here: https://github.com/stkenny/OpenRefine/tree/jetty9_migration

**Comment by wetneb** [comment]
@stkenny it looks like you have closed this PR without merging it - was it intentional? It would be fantastic if this extension could work with OR 2.7. We have just dropped Oracle JDK 7 support as it has reached its end of life.

**Pull request closed without merging**
